### ISSUE TITLE
Access for hierauser is not granted

### ISSUE THREAD

**Issue by slobodanz** [atomia/puppet-atomia#126]
It seems that create user command is not executed during initial installation and deploying nodes fails with:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Access denied for user 'hierauser'@'localhost' (using password: YES
) at /etc/puppet/manifests/site.pp:3:9 on node

If command is executed manually everything works
https://github.com/atomia/puppet-atomia/blob/master/setup-puppet-atomia#L26

**Comment by stefanmortensen** [comment]
Needed a flush privileges.

https://github.com/atomia/puppet-atomia/commit/b351b7d2289c18f7470a7a97bed1ffe3bf0e5051
