### ISSUE TITLE
MySQL privileges not correct

### ISSUE THREAD

**Issue by Smiliebg** [atomia/puppet-atomia#139]
After installation MySQL user did not have grant option privileges;
this results in error that MySQL user can create table, but was not able to assign users (as defined in HCP) to the newly created table.

Extending privileges with 'WITH GRANT OPTION'  at the end of the grant statement has solved the issue.

**Comment by stefanmortensen** [comment]
What manifest is this referring to? If it is the mysql manifest the grant option should already be set to the provisioning user see

https://github.com/atomia/puppet-atomia/blob/master/manifests/mysql.pp#L44-L50

I'll check if I can reproduce

**Comment by Smiliebg** [comment]
Yes, that is the manifest;

I was not able to try to reproduce it - I had no environment where to test it, so fixed it manually.

**Comment by stefanmortensen** [comment]
```
mysql> show grants for 'mysqladmin'@'192.168.33.10';
+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Grants for mysqladmin@192.168.33.10                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'mysqladmin'@'192.168.33.10' IDENTIFIED BY PASSWORD '*F861720E101148897B0F5239DB926E756B1C28B3' WITH GRANT OPTION |
+--------------------------------------------------------------------------------------------------------------------------------------------------+

logged in as that user

create database foo;
/* Affected rows: 1  Found rows: 0  Warnings: 0  Duration for 1 query: 0.000 sec. */
create user 'foobar'@'localhost' IDENTIFIED BY 'foobar';
/* Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 1 query: 0.000 sec. */
GRANT ALL ON foo.* TO 'foobar'@'localhost';
SHOW grants for 'foobar'@'localhost';
"Grants for foobar@localhost"
"GRANT USAGE ON *.* TO 'foobar'@'localhost' IDENTIFIED BY PASSWORD '*9B500343BC52E2911172EB52AE5CF4847604C6E5'"
"GRANT ALL PRIVILEGES ON `foo`.* TO 'foobar'@'localhost'" 
```

So to me it looks like this is working so I'm gonna have to say works for me here :). If you have any further info that shows otherwise or steps to reproduce feel free to add a new comment here.
