### ISSUE TITLE
unattended.ini

### ISSUE THREAD

**Issue by markotrickovic** [atomia/puppet-atomia#140]
Puppet does not put "BccEmailAddressesList = " in unattended.ini (Email section).

**Comment by stefanmortensen** [comment]
You resolved this with a PR it looks like?

**Comment by stefanmortensen** [comment]
If this is not resolved with https://github.com/atomia/puppet-atomia/commit/43e0ab8b31ff68d61c454c84abc5aed942036913 please reopen issue
