### ISSUE TITLE
Internal DNS on private IP range

### ISSUE THREAD

**Issue by Smiliebg** [atomia/puppet-atomia#142]
Due to the nature of Internal DNS (configuring all other servers) it has by default BIND installed with recursive on and allow-query { all; }

In case customer installs this role on Public ONLY IP address it is just a matter of time before amplified DDoS starts acting on it.

Please change manifest to either:

1. Not allow installation if server has no private IP address;
2. As alternative, allow Public IP, but set firewall / BIND allow-query rules to allow only Atomia related servers to be able to query this BIND installation.

**Comment by stefanmortensen** [comment]
We should do 2, this will introduce a new variable (ip_range) to the basic configuration step which should then be used here.
