### ISSUE TITLE
Link atomia-pa-apache.conf is not in conf-enabled

### ISSUE THREAD

**Issue by markotrickovic** [atomia/puppet-atomia#144]
Apache-agent script doesn't create atomia-pa-apache.conf link.

This link should point to file: /etc/apache2/conf-available/atomia-pa-apache.conf.ubuntu.1404

**Comment by stefanmortensen** [comment]
I know it's not a link but meh :) https://github.com/atomia/puppet-atomia/blob/master/manifests/apache_agent.pp#L152-L157

Looks like it should work with the above? Or did you experience any issues relating to this?

**Comment by markotrickovic** [comment]
This ${pa_conf_available_path} is conf-available.

**Comment by stefanmortensen** [comment]
Sorry I am not following :). That is the new conf path for apache 2.4+. Is your problem with this that this is an acutal file and not a symlink? Please elaborate.

**Comment by stefanmortensen** [comment]
Ah I see it now! The conf file is created as "atomia-pa-apache.conf.ubuntu.1404" when it should simply be atomia-pa-apache.conf doh! I'll fix, thanks!
