### ISSUE TITLE
Atomia does not like PGSQL v9.3

### ISSUE THREAD

**Issue by markotrickovic** [atomia/puppet-atomia#153]
Database creation throurgh Atomia works perfectly.
Database deletion fails with:
    ID428002: Service PostgreSQLDatabase: error: ERROR: 42703: column "procpid" does not exist

The thing is: after pgsql v9.2, this column is called "pid" not "procpid".

I know this is issue for other people, but let be noted here while isn't fixed.

Workarround:
echo "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
apt-get update
apt-get install postgresql-9.1
# config & create user

**Comment by stefanmortensen** [comment]
I could not find a bug report for this internally. Did you file a bug report for it? I agree that this is an issue that should be solved elsewhere :)

**Comment by markotrickovic** [comment]
Nope, did not done that.

**Comment by stefanmortensen** [comment]
Posted an issue on your behalf in the bug tracker

**Comment by markotrickovic** [comment]
<3

**Comment by jimmybergman** [comment]
This is since fixed
