### ISSUE TITLE
On grouping roles make sure no conflict will arrise

### ISSUE THREAD

**Issue by Smiliebg** [atomia/puppet-atomia#159]
Installation wizard now supports multiple roles per server, please make sure that customer can not install conflicting roles per server;

for example, Internal DNS and Name Servers can not exist on same machine due to conflict on port 53.

Not sure if other conflicts may exists?

**Comment by stefanmortensen** [comment]
Move this to puppetmaster-gui https://github.com/atomia/puppetmaster-gui/issues/63
