### ISSUE TITLE
Installation checks

### ISSUE THREAD

**Issue by Smiliebg** [atomia/puppet-atomia#160]
Please implement (on some level / at some point before / during installation) following checks:

- are all network requirements satisfied (servers can reach each other on required ports and are all host names FQDN);

- Are Windows servers in English language;

- Is Puppet master white listed / allowed to Atomia repositories;

- Internal DNS must either be on private IP address only - or if this is not possible must be properly firewalled to prevent DNS amplified DDoS attacks;

- Are all Linux / supporting applications up to date (apt-get);

- Present customer with information regarding licenses during the installation process (Ie. Installatron, MSSQL and so on);

- Is network resolving on all machines OK;

- NTP on all servers is correctly set up;

- Windows Servers have installed .NET Framework 4.6.1

**Comment by stefanmortensen** [comment]
Moved this to https://github.com/atomia/puppetmaster-gui/issues/41 where it belongs
