### ISSUE TITLE
Define default language(s) and currencie(s)

### ISSUE THREAD

**Issue by Smiliebg** [atomia/puppet-atomia#162]
One of the tasks that is every single time executed post installation is configuring languages and currencies to be used.

Please add this as (last?) step in the installation wizard with nice check boxes for languages and currencies. Upon provisioning update DB accordingly to the selected choices.

**Comment by stefanmortensen** [comment]
Moved to puppetmaster-gui https://github.com/atomia/puppetmaster-gui/issues/64
