### ISSUE TITLE
Incorrect default values for Internal DNS

### ISSUE THREAD

**Issue by osm** [atomia/puppet-atomia#166]
The field "allow_query" has the value "any" set, it should be "any;". With the default value set the named-checkconf validation fails.

root@ip-10-0-0-189:/etc/bind# named-checkconf 
/etc/bind/named.conf.options:2: missing ';' before '}'

**Comment by oscarlinderholm** [comment]
The field "ip_address" under the advanced configuration has the value "$ipaddress". If this is not changed it be put in other nodes /etc/resolv.conf.

This should either be made a mandatory field or set the ip address of the machine that the internal DNS is provisioned to.

**Comment by stefanmortensen** [comment]
The $ipaddress is automatically expanded to the actual ip of the machine by doing a lookup on the hostname. If this fails for whatever reason it looks like it will keep using $ipaddress. We should treat this as invalid input for the form and fall back to manually entering the ip if the lookup fails.

**Comment by stefan-strandberg** [comment]
Good to see this one closed, finally 🙂
