### ISSUE TITLE
Puppet master setup-puppet-atomia script still doesn't grant privilages to hierauser

### ISSUE THREAD

**Issue by slobodanz** [atomia/puppet-atomia#169]
Initial installation of puppet GUI end with error:

ERROR 1396 (HY000) at line 1: Operation DROP USER failed for 'puppetgui'@'localhost'

and later deploying nodes fails with error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Access denied for user 'hierauser'@'localhost' (using password: YES) at /etc/puppet/manifests/site.pp:3:9 on node

**Comment by stefanmortensen** [comment]
We've done a couple of installations lately where this did not happen. Was there any other error that might have lead to the access denied error? How did you resolve it?
