### ISSUE TITLE
The Filesystem Agent requires ruby 2.0

### ISSUE THREAD

**Issue by oscarlinderholm** [atomia/puppet-atomia#170]
The Filesystem Agent requires ruby 2.0

**Comment by stefanmortensen** [comment]
Default ruby version in 16.04 is 2.3. I assume that the problem you are referring to is the jgrep who has a set requirement on 1.9.1

>   package { ['jgrep']:
>     ensure   => installed,
>     provider => 'gem',
>     require  => [Package['ruby1.9.1-dev']],
>   }

Also see #138
