### ISSUE TITLE
atomiastatisticscopy fails to run on CloudLinux machines

### ISSUE THREAD

**Issue by nbeernink** [atomia/puppet-atomia#174]
procmail isn't provisioned and resulting in the failure to run

```
* * * * *	root	lockfile -r0 /var/run/atomiastatisticscopy.lock && (atomiastatisticscopy; rm /var/run/atomiastatisticscopy.lock)
```

```
lockfile command not found
```

Solutions:
1. Could ensure procmail package is installed
2. Could use flock provided by util-linux which is installed

**Comment by jimmybergman** [comment]
This is resolved with atomiastatisticscopy 1.0.7 that now uses flock for this cron-entry.
