### ISSUE TITLE
puppet fails when trying to provision a manifest on 16.04

### ISSUE THREAD

**Issue by zeljko-atomia** [atomia/puppet-atomia#184]
This the debug run log from failing provisioning run:

`Debug: Failed to load library 'msgpack' for feature 'msgpack'
Debug: Puppet::Network::Format[msgpack]: feature msgpack is missing
Debug: catalog supports formats: pson yaml b64_zlib_yaml dot raw
Debug: Using cached connection for https://ip-10-0-0-60.eu-west-1.compute.internal:8140
Debug: Caching connection for https://ip-10-0-0-60.eu-west-1.compute.internal:8140
Error: Could not retrieve catalog from remote server: Could not intern from text/pson: wrong number of arguments (given 2, expected 1)
/usr/lib/ruby/vendor_ruby/facter/atomia_role.rb:46:in `open'
/usr/lib/ruby/2.3.0/rubygems/stub_specification.rb:113:in `data'
/usr/lib/ruby/2.3.0/rubygems/stub_specification.rb:204:in `valid?'
/usr/lib/ruby/2.3.0/rubygems/specification.rb:749:in `select'
/usr/lib/ruby/2.3.0/rubygems/specification.rb:749:in `gemspec_stubs_in'
/usr/lib/ruby/2.3.0/rubygems/specification.rb:756:in `default_stubs'
/usr/lib/ruby/2.3.0/rubygems/specification.rb:831:in `stubs'
/usr/lib/ruby/2.3.0/rubygems/specification.rb:725:in `_all'
/usr/lib/ruby/2.3.0/rubygems/specification.rb:1123:in `latest_specs'
/usr/lib/ruby/vendor_ruby/puppet/util/rubygems.rb:44:in `directories'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:160:in `gem_directories'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:164:in `search_directories'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:89:in `get_file'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:58:in `load_file'
/usr/lib/ruby/vendor_ruby/puppet/util/autoload.rb:199:in `load'
/usr/lib/ruby/vendor_ruby/puppet/metatype/manager.rb:163:in `type'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:277:in `resource_type'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:243:in `initialize'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:33:in `new'
/usr/lib/ruby/vendor_ruby/puppet/resource.rb:33:in `from_data_hash'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:342:in `block in from_data_hash'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:341:in `collect'
/usr/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:341:in `from_data_hash'
/usr/lib/ruby/vendor_ruby/puppet/util/pson.rb:11:in `pson_create'
/usr/lib/ruby/vendor_ruby/puppet/external/pson/pure/parser.rb:305:in `parse_object'
/usr/lib/ruby/vendor_ruby/puppet/external/pson/pure/parser.rb:98:in `parse'
/usr/lib/ruby/vendor_ruby/puppet/external/pson/common.rb:133:in `parse'
/usr/lib/ruby/vendor_ruby/puppet/network/formats.rb:143:in `intern'
/usr/lib/ruby/vendor_ruby/puppet/network/format_support.rb:12:in `convert_from'
/usr/lib/ruby/vendor_ruby/puppet/indirector/rest.rb:245:in `deserialize_find'
/usr/lib/ruby/vendor_ruby/puppet/indirector/rest.rb:103:in `find'
/usr/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:294:in `block in retrieve_new_catalog'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:335:in `block in thinmark'
/usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:334:in `thinmark'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:293:in `retrieve_new_catalog'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:61:in `retrieve_catalog'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:106:in `prepare_and_retrieve_catalog'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:202:in `run_internal'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:134:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/context.rb:64:in `override'
/usr/lib/ruby/vendor_ruby/puppet.rb:246:in `override'
/usr/lib/ruby/vendor_ruby/puppet/configurer.rb:133:in `run'
/usr/lib/ruby/vendor_ruby/puppet/agent.rb:47:in `block (4 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/agent/locker.rb:20:in `lock'
/usr/lib/ruby/vendor_ruby/puppet/agent.rb:47:in `block (3 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/agent.rb:117:in `with_client'
/usr/lib/ruby/vendor_ruby/puppet/agent.rb:44:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/agent.rb:82:in `run_in_fork'
/usr/lib/ruby/vendor_ruby/puppet/agent.rb:43:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:179:in `controlled_run'
/usr/lib/ruby/vendor_ruby/puppet/agent.rb:41:in `run'
/usr/lib/ruby/vendor_ruby/puppet/application/agent.rb:361:in `onetime'
/usr/lib/ruby/vendor_ruby/puppet/application/agent.rb:327:in `run_command'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block (2 levels) in run'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:507:in `plugin_hook'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `block in run'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:496:in `exit_on_fail'
/usr/lib/ruby/vendor_ruby/puppet/application.rb:381:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:146:in `run'
/usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:92:in `execute'
/usr/bin/puppet:8:in `<main>'
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

**Comment by stefanmortensen** [comment]
most likely due to non matching puppet versions on master/client. Expecting this to go away after the master is updated to 16.4

**Comment by stefanmortensen** [comment]
Seems like this was due to some changes in how the atomia_role.rb script is being handled in ruby 2.3. I have resolved this issue and will have an updated version of this in the develop branch shortly.  If you would like to pursue your adventures with 16.4 prior to the new installer being done feel free to copy it onto your server.
