### ISSUE TITLE
apache 2.4.7 version upgrade

### ISSUE THREAD

**Issue by slobodanz** [atomia/puppet-atomia#43]
Default DocumentRoot is /var/www/html, not /var/www

Deafult apache2.conf doesn't include conf.d/, 
add in apache2.conf    IncludeOptional conf.d/

**Comment by stefanmortensen** [comment]
Resolved with https://github.com/atomia/puppet-atomia/commit/832a1732ddd0e5dc461c44b1c0ce0698574e2df9
