### ISSUE TITLE
ways to improve code quality

### ISSUE THREAD

**Issue by nbeernink** [atomia/puppet-atomia#73]
The past few days I've worked on your puppet code in an attempt to add support for CentOS mail servers. This was somewhat hampered because the files have non-standard formatting, in some places is full of unnecessary white-space/tabs (which shows up glaring red in my editor ;)) and in some places are quite hard to read.

In order to improve the code the following could be done:

* Follow guidelines as described in https://docs.puppet.com/guides/style_guide.html, this is easy to do with some minor tweaks to the editor of your choice. (in my case I use vim with  https://github.com/scrooloose/syntastic)
* I noticed someone tried to hook up https://travis-ci.org/ for automated testing but never seemed to get it to work. Having this, even for basic validation and syntax checking, can be a big help on making sure your code doesn't break.

If you need help let me know! I'd be happy to help out.

![pretty-puppet-atomia-code](https://cloud.githubusercontent.com/assets/652353/15424228/cc270002-1e81-11e6-8826-a303a6e52289.png)

**Comment by stefanmortensen** [comment]
Thanks for your input I really appreciate your contributions to the module.

I totally agree with the need for a common code style throughout the project and I will look into hooking it up to a CI system again as well as converting the project to conform to a common style. If you want to help out with this I am all for it :+1:.
  
We do have some specs that could be run as well, earlier I had the ambition to run full integration tests through Beaker but it was never fully set up however it would be tremendously useful especially for testing on multiple platforms.

**Comment by nbeernink** [comment]
Okay, updated the travis setup for you guys; https://github.com/atomia/puppet-atomia/pull/75, obviously it fails due to the current state of the code. But those things could be fixed to make it better. :+1: 

Are you still using eclipse for puppet-atomia development? Perhaps you could have a look at https://puppet.com/blog/geppetto-a-puppet-ide which seems to be based on eclipse and centered around puppet. (no experience with it, I just saw the .project file and it was the first hit for eclipse + puppet ;))

I think adding beaker support would be awesome for the same reasons you mention.

**Comment by stefanmortensen** [comment]
Thanks for that I merged it.

I was previously using Gepetto but has moved away from it. Now I am using Atom or VS Code.

**Comment by nbeernink** [comment]
Alright. A quick google search tells me that both of those editors have plugins for puppet code syntax checking available. Perhaps worth checking out if you guys are not already using them. :)

I think it would be fairly easy (albeit a little time consuming if done manually) to clean up all the code and get travis to show that green badge for us. I am having trouble seeing a good way to approach the whole process though, it could be done by either cleaning up everything in one go or do it one file at a time. 

Either way, extra care should be taken that cleaning up does not mean breaking things. This testing could be done manually or additional time could be put in to make sure our beloved beaker support is  added.

I had a look at http://opensource.mtier.org/ptidy.html to clean it automatically. But unfortunately it seems it is no longer actively developed. I tried an older version but couldn't get it to work. :(

**Comment by nbeernink** [comment]
I just discovered that puppet-lint actually has a `--fix` option that we may be able to utilize and could fix most of the issues. Perhaps we can semi-automatically fix the code with a simple script. Something I just knocked together rather brutish:

```
for manifest in $(find manifests/ -type f -iname '*.pp'); do
  sed -i 's/[ \t]*$//' $manifest #strip whitespace
  vim -c 'normal gg=G' -c 'wq' $manifest
  puppet-lint --no-80chars-check --no-documentation-check --fix $manifest
done
```

Need to be extra careful before the commit is done though. What are your thoughts on all this?

**Comment by stefanmortensen** [comment]
I'm now running a linter in my editor and all future contributions will have to pass through CI before merge. Once again thanks for your contribution :+1:
